# Generated by Django 2.1.1 on 2018-11-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
