# Generated by Django 2.1.1 on 2019-07-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapi', '0003_auto_20181112_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='coin',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('iota', 'IOTA'), ('xmr', 'Monero')], max_length=8, unique=True, verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('insufficient', 'Payment Insufficient'), ('received', 'Received'), ('done', 'Done')], default='', max_length=16, null=True, verbose_name='Status'),
        ),
    ]
