# Generated by Django 3.0.2 on 2020-05-04 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapi', '0004_auto_20190729_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='coin',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('iota', 'IOTA'), ('xmr', 'Monero'), ('erc20_usdt', 'ERC-20 USDT'), ('erc20_bcz', 'ERC-20 BECAZ')], max_length=16, unique=True, verbose_name='Coin'),
        ),
    ]
