# Generated by Django 3.0.6 on 2020-08-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapi', '0006_auto_20200505_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='coin',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('bch', 'Bitcoin Cash'), ('ltc', 'Litecoin'), ('iota', 'IOTA'), ('xmr', 'Monero'), ('erc20_usdt', 'ERC-20 USDT'), ('erc20_usdc', 'ERC-20 USDC'), ('erc20_busd', 'ERC-20 BUSD'), ('erc20_pax', 'ERC-20 PAX'), ('erc20_tusd', 'ERC-20 TUSD'), ('erc20_bnb', 'ERC-20 BNB'), ('erc20_link', 'ERC-20 ChainLink'), ('erc20_cro', 'ERC-20 Crypto.com Coin'), ('erc20_mkr', 'ERC-20 Maker'), ('erc20_nexo', 'ERC-20 NEXO'), ('erc20_bcz', 'ERC-20 BECAZ')], max_length=16, unique=True, verbose_name='Coin'),
        ),
    ]
