# Generated by Django 4.0.4 on 2022-05-25 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptapi', '0007_auto_20200827_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.JSONField(default=dict, max_length=5048)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Meta Data',
                'verbose_name_plural': 'Meta Data',
            },
        ),
        migrations.AlterField(
            model_name='provider',
            name='coin',
            field=models.CharField(max_length=16, unique=True, verbose_name='Coin'),
        ),
        migrations.AlterField(
            model_name='request',
            name='value_requested',
            field=models.DecimalField(decimal_places=18, default=0, max_digits=65, verbose_name='Value Requested'),
        ),
    ]
